---
title: "Welcome to the Lab"
page-navigation: false
listing:
  - id: events
    contents: "events/*qmd"
    type: default
    sort: "event-date desc"
    fields: [event-date, event-location, image, title, description]
  - id: news
    sort: "news-date desc"
    contents: "news/*qmd"
    type: grid
    fields: [image, title, description]

---

The MIND Lab is based in the Department of Psychology at Teesside University. The lab is co-led by Dr Christopher Wilson and Dr Srdan Medimorec. Our lab was launched in 2024 and our website in 2025.

The MIND Lab's work is organised into two primary research streams, each led by a Principal Investigator.

::: columns
::: {.column width="50%"}

Dr. Christopher Wilson's Research Programme: 

The Cognitive Neuroscience of Risk & Gambling Harms.

[Learn more about gambling research here](research/gambling.qmd){.btn .btn-success}

:::
::: {.column width="50%"}

Dr. Medimorec's Research Programme: 

language, meta-cognition, implicit learning. 

[Learn more about language and learning research here](research/languageandlearning.qmd){.btn .btn-success}

:::
:::
We use a range of methods, including functional near-infrared spectroscopy (fNIRS), eye-tracking, and virtual reality, to study these processes in both healthy and clinical populations.


::: {.callout}
## Joining the lab

If you are interested in joining the lab, the fist step is reading the [Lab Manual](info/lab_manual.html). This will give you an overview of the lab's research, methods, and culture.

:::

## Lab News

::: {#news}
:::

## Lab Events

::: {#events}
:::


